import { describe, expect, it } from 'vitest'
import { pickPreferredBranchName } from './non-interactive'

describe('create-branch non-interactive', () => {
  it('picks the first branch suggestion', () => {
    const result = pickPreferredBranchName([
      'feat/PROJ-123-add-auth',
      'feat/PROJ-123-implement-auth',
    ])

    expect(result).toBe('feat/PROJ-123-add-auth')
  })

  it('throws when no branch suggestion is available', () => {
    expect(() => pickPreferredBranchName([])).toThrow(
      'No valid branch name generated by AI',
    )
  })
})
