export function pickPreferredBranchName(branchNames: string[]): string {
  const selected = branchNames[0]?.trim()
  if (!selected) {
    throw new Error('No valid branch name generated by AI')
  }

  return selected
}
