import { describe, expect, it } from 'vite-plus/test'
import {
  AUTO_COMMIT_TYPE,
  assertJiraRequiresType,
  pickPreferredCommitMessage,
  resolveCommitType,
} from './non-interactive'

describe('ai-commit non-interactive', () => {
  it('uses auto commit type in non-interactive mode', () => {
    expect(resolveCommitType(undefined, true)).toBe(AUTO_COMMIT_TYPE)
    expect(resolveCommitType(undefined, true)).toBe(AUTO_COMMIT_TYPE)
  })

  it('normalizes provided commit type', () => {
    expect(resolveCommitType('FIX', false)).toBe('fix')
  })

  it('throws for unsupported commit type', () => {
    expect(() => resolveCommitType('invalid', true)).toThrow(
      'Unsupported commit type: invalid',
    )
  })

  it('picks the first generated commit message', () => {
    expect(
      pickPreferredCommitMessage(['feat: add login', 'feat: implement auth']),
    ).toBe('feat: add login')
  })

  it('throws when commit messages are empty', () => {
    expect(() => pickPreferredCommitMessage([])).toThrow(
      'No commit message generated by AI',
    )
  })

  describe('assertJiraRequiresType', () => {
    it('throws when --jira + --non-interactive without --type', () => {
      expect(() =>
        assertJiraRequiresType({
          jira: 'PROJ-123',
          nonInteractive: true,
          type: undefined,
        }),
      ).toThrow(
        '--type is required when using --jira with --non-interactive/--ci',
      )
    })

    it('throws when --jira is true (branch detection) + --non-interactive without --type', () => {
      expect(() =>
        assertJiraRequiresType({
          jira: true,
          nonInteractive: true,
          type: undefined,
        }),
      ).toThrow(
        '--type is required when using --jira with --non-interactive/--ci',
      )
    })

    it('does not throw when --type is provided', () => {
      expect(() =>
        assertJiraRequiresType({
          jira: 'PROJ-123',
          nonInteractive: true,
          type: 'feat',
        }),
      ).not.toThrow()
    })

    it('does not throw when not in non-interactive mode', () => {
      expect(() =>
        assertJiraRequiresType({
          jira: 'PROJ-123',
          nonInteractive: false,
          type: undefined,
        }),
      ).not.toThrow()
    })

    it('does not throw when --jira is not used', () => {
      expect(() =>
        assertJiraRequiresType({
          jira: undefined,
          nonInteractive: true,
          type: undefined,
        }),
      ).not.toThrow()
    })
  })
})
