import { describe, expect, it } from 'vitest'
import {
  AUTO_COMMIT_TYPE,
  pickPreferredCommitMessage,
  resolveCommitType,
} from './non-interactive'

describe('ai-commit non-interactive', () => {
  it('uses auto commit type in non-interactive mode', () => {
    expect(resolveCommitType(undefined, true)).toBe(AUTO_COMMIT_TYPE)
    expect(resolveCommitType(undefined, true)).toBe(AUTO_COMMIT_TYPE)
  })

  it('normalizes provided commit type', () => {
    expect(resolveCommitType('FIX', false)).toBe('fix')
  })

  it('throws for unsupported commit type', () => {
    expect(() => resolveCommitType('invalid', true)).toThrow(
      'Unsupported commit type: invalid',
    )
  })

  it('picks the first generated commit message', () => {
    expect(
      pickPreferredCommitMessage(['feat: add login', 'feat: implement auth']),
    ).toBe('feat: add login')
  })

  it('throws when commit messages are empty', () => {
    expect(() => pickPreferredCommitMessage([])).toThrow(
      'No commit message generated by AI',
    )
  })
})
