export const SUPPORTED_COMMIT_TYPES = [
  'feat',
  'fix',
  'docs',
  'style',
  'refactor',
  'perf',
  'test',
  'chore',
  'ci',
  'build',
] as const

export const AUTO_COMMIT_TYPE = 'auto'

export function assertJiraRequiresType(options: {
  jira?: string | boolean
  nonInteractive: boolean
  type?: string
}): void {
  if (options.jira && options.nonInteractive && !options.type) {
    throw new Error(
      '--type is required when using --jira with --non-interactive/--ci',
    )
  }
}

export function resolveCommitType(
  commitType: string | undefined,
  nonInteractive: boolean,
): string | undefined {
  if (!commitType) {
    if (!nonInteractive) {
      return undefined
    }

    return AUTO_COMMIT_TYPE
  }

  const normalizedType = commitType.trim().toLowerCase()
  if (
    !SUPPORTED_COMMIT_TYPES.includes(
      normalizedType as (typeof SUPPORTED_COMMIT_TYPES)[number],
    )
  ) {
    throw new Error(`Unsupported commit type: ${commitType}`)
  }

  return normalizedType
}

export function pickPreferredCommitMessage(commitMessages: string[]): string {
  const selected = commitMessages[0]?.trim()
  if (!selected) {
    throw new Error('No commit message generated by AI')
  }

  return selected
}
